### ISSUE TITLE
Fill out the README

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/dockerhub#2]
@tampakis I wonder where the best place to document these would be. Would it make sense (and would it not break anything) to put a README.md in each directory within the images directory? Does docker have a convention?

**Comment by tampakis** [comment]
Readmes for each image should live with the Dockerfile. Updates pushed to the Github repo will also send a message to Docker Hub to update and rebuild the image. The readme also is linked to the [Docker Hub page](https://registry.hub.docker.com/u/tampakis/solr_tomcat/) for each specific image.
